terrain/sun.png = assets/alphaver/textures/environment/sun.png
terrain/sun_n.png = assets/alphaver/textures/environment/sun_nebula.png
terrain/moon.png = assets/alphaver/textures/environment/moon.png
terrain/moon_n.png = assets/alphaver/textures/environment/moon_nebula.png
terrain/hub_parallax3.png = assets/alphaver/textures/environment/hub_parallax.png

mob/observer.png = assets/alphaver/textures/entity/observer/0.png
mob/collosal_a.png = assets/alphaver/textures/entity/colossus/0.png
mob/amoung.png = assets/alphaver/textures/entity/amoung/0.png
mob/catbomb.png = assets/alphaver/textures/entity/catbomb/0.png
mob/kill_squid.png = assets/alphaver/textures/entity/squib/0.png
mob/pongt.png = assets/alphaver/textures/entity/pongormatron/0.png
mob/spearmaster.png = assets/alphaver/textures/entity/spearmaster/0.png
saltsven.png = assets/alphaver/textures/entity/salt_sven/0.png
item/spearprojectile.png = assets/alphaver/textures/entity/spear/spear.png
armor/obsidian_1.png = assets/alphaver/textures/armor/obsidian_1.png
armor/obsidian_2.png = assets/alphaver/textures/armor/obsidian_2.png
armor/stylish_1.png = assets/alphaver/textures/armor/stylish_1.png
armor/stylish_2.png = assets/alphaver/textures/armor/stylish_2.png
armor/fashion_1.png = assets/alphaver/textures/armor/fashion_1.png
item/essenceprojectile.png = assets/alphaver/textures/entity/essence_shot/essence_shot.png

gui/freezer.png = assets/alphaver/textures/gui/freezer.png
gui/essencetransformer.png = assets/alphaver/textures/gui/essence_transformer.png
gui/essencecloner.png = assets/alphaver/textures/gui/essence_cloner.png
sounddata/streaming/sandcastles.ogg = resources/alphaver/sounds/record/sandcastles.ogg
sounddata/streaming/RokkubitoruTune.ogg = resources/alphaver/sounds/record/RokkubitoruTune.ogg
sounddata/streaming/downbeat_uplink.ogg = resources/alphaver/sounds/record/downbeat_uplink.ogg
sounddata/streaming/K2.ogg = resources/alphaver/sounds/record/K2.ogg
sounddata/streaming/desambrier.ogg = resources/alphaver/sounds/record/desambrier.ogg
sounddata/streaming/Juhry.ogg = resources/alphaver/sounds/record/Juhry.ogg
sounddata/streaming/GyldanSverd.ogg = resources/alphaver/sounds/record/GyldanSverd.ogg
sounddata/newsound/ext/dash.wav = resources/alphaver/sounds/ext/dash.wav
sounddata/newsound/ext/marior.ogg = resources/alphaver/sounds/ext/marior.ogg
sounddata/newsound/ext/recharg.ogg = resources/alphaver/sounds/ext/recharg.ogg
sounddata/newsound/ext/obvr_spawn.ogg = resources/alphaver/sounds/ext/obvr_spawn.ogg
sounddata/newsound/ext/obvr_attack.ogg = resources/alphaver/sounds/ext/obvr_attack.ogg
sounddata/newsound/ext/giantambient.ogg = resources/alphaver/sounds/ext/giantambient.ogg
sounddata/newsound/ext/gianthit1.ogg = resources/alphaver/sounds/ext/gianthit1.ogg
sounddata/newsound/ext/gianthit2.ogg = resources/alphaver/sounds/ext/gianthit2.ogg
sounddata/newsound/ext/giantdead.ogg = resources/alphaver/sounds/ext/giantdead.ogg
sounddata/newsound/ext/notif.ogg = resources/alphaver/sounds/ext/notif.ogg
sounddata/newsound/ext/notiftex.ogg = resources/alphaver/sounds/ext/notiftex.ogg
sounddata/newsound/ext/infuse.ogg = resources/alphaver/sounds/ext/infuse.ogg
sounddata/newsound/ext/useflame.ogg = resources/alphaver/sounds/ext/useflame.ogg
sounddata/newsound/ext/hitmarker.wav = resources/alphaver/sounds/ext/hitmarker.wav
sounddata/newsound/ext/flower_boom.ogg = resources/alphaver/sounds/ext/flower_boom.ogg
sounddata/newsound/random/riff.ogg = resources/alphaver/sounds/random/riff.ogg
sounddata/newsound/step/glass1.ogg = resources/alphaver/sounds/step/glass1.ogg
sounddata/newsound/step/glass2.ogg = resources/alphaver/sounds/step/glass2.ogg
sounddata/newsound/step/glass3.ogg = resources/alphaver/sounds/step/glass3.ogg
sounddata/newsound/step/glass4.ogg = resources/alphaver/sounds/step/glass4.ogg
sounddata/newsound/step/special1.ogg = resources/alphaver/sounds/step/special1.ogg
sounddata/newsound/step/special2.ogg = resources/alphaver/sounds/step/special2.ogg
sounddata/newsound/step/special3.ogg = resources/alphaver/sounds/step/special3.ogg
sounddata/newsound/step/special4.ogg = resources/alphaver/sounds/step/special4.ogg
sounddata/newsound/step/elder1.ogg = resources/alphaver/sounds/step/elder1.ogg
sounddata/newsound/step/elder2.ogg = resources/alphaver/sounds/step/elder2.ogg
sounddata/newsound/step/elder3.ogg = resources/alphaver/sounds/step/elder3.ogg
sounddata/newsound/step/elder4.ogg = resources/alphaver/sounds/step/elder4.ogg
sounddata/streaming/lemuria.ogg = resources/alphaver/sounds/record/lemuria.ogg
sounddata/streaming/hidden_den.ogg = resources/alphaver/sounds/record/hidden_den.ogg

sounddata/music/last_autumn.ogg = resources/alphaver/sounds/music/last_autumn.ogg
sounddata/music/ballroom_pianist.ogg = resources/alphaver/sounds/music/ballroom_pianist.ogg
sounddata/music/moon_2.ogg = resources/alphaver/sounds/music/moon_2.ogg
sounddata/music/nordic_sanctuary.ogg = resources/alphaver/sounds/music/nordic_sanctuary.ogg
sounddata/music/norway.ogg = resources/alphaver/sounds/music/norway.ogg
sounddata/music/sadway.ogg = resources/alphaver/sounds/music/sadway.ogg
sounddata/music/m43343138.ogg = resources/alphaver/sounds/music/m43343138.ogg
sounddata/music/before_the_storm.ogg = resources/alphaver/sounds/music/before_the_storm.ogg
sounddata/music/Stormclouds.ogg = resources/alphaver/sounds/music/Stormclouds.ogg
sounddata/music/denmark.ogg = resources/alphaver/sounds/music/denmark.ogg
sounddata/music/estonian_reliquary.ogg = resources/alphaver/sounds/music/estonian_reliquary.ogg
sounddata/music/sunrise_at_denmark.ogg = resources/alphaver/sounds/music/sunrise_at_denmark.ogg
sounddata/music/emergent_gods_of_helsinki.ogg = resources/alphaver/sounds/music/emergent_gods_of_helsinki.ogg
sounddata/music/Branches_Cycling.ogg = resources/alphaver/sounds/music/Branches_Cycling.ogg
sounddata/music/Counting_Grains_of_Sand.ogg = resources/alphaver/sounds/music/Counting_Grains_of_Sand.ogg
sounddata/music/SynestheticRodents.ogg = resources/alphaver/sounds/music/SynestheticRodents.ogg
sounddata/music/Isometry.ogg = resources/alphaver/sounds/music/Isometry.ogg
sounddata/music/CoralRifts.ogg = resources/alphaver/sounds/music/CoralRifts.ogg
sounddata/music/Stuttering.ogg = resources/alphaver/sounds/music/Stuttering.ogg
sounddata/music/Stahlvogel.ogg = resources/alphaver/sounds/music/Stahlvogel.ogg
sounddata/music/clouded_city.ogg = resources/alphaver/sounds/music/clouded_city.ogg
sounddata/music/Dongbaekkot.ogg = resources/alphaver/sounds/music/Dongbaekkot.ogg
sounddata/music/QuetzalcoatlArrives.ogg = resources/alphaver/sounds/music/QuetzalcoatlArrives.ogg
sounddata/music/ReflectedSapphire.ogg = resources/alphaver/sounds/music/ReflectedSapphire.ogg
sounddata/music/FrozenMushrooms.ogg = resources/alphaver/sounds/music/FrozenMushrooms.ogg
sounddata/music/Tear_Monoliths.ogg = resources/alphaver/sounds/music/Tear_Monoliths.ogg
sounddata/music/TogetherWeStandAsOne.ogg = resources/alphaver/sounds/music/TogetherWeStandAsOne.ogg
sounddata/music/PerfectedMonastery.ogg = resources/alphaver/sounds/music/PerfectedMonastery.ogg
sounddata/music/JerichoNazarethJunction.ogg = resources/alphaver/sounds/music/JerichoNazarethJunction.ogg
sounddata/music/StarlessBethlehem.ogg = resources/alphaver/sounds/music/StarlessBethlehem.ogg

sounddata/hub/Prophecy_of_the_Holy_Epiphora.ogg = resources/alphaver/sounds/hub/Prophecy_of_the_Holy_Epiphora.ogg
sounddata/hub/Starless_Bethlehem.ogg = resources/alphaver/sounds/hub/Starless_Bethlehem.ogg
sounddata/hub/neural_convergence.ogg = resources/alphaver/sounds/hub/neural_convergence.ogg
