terrain.png#170 = assets/alphaver/textures/block/salt_block_top.png
terrain.png#169 = assets/alphaver/textures/block/salt_block_side.png
terrain.png#171 = assets/alphaver/textures/block/water_lily.png
terrain.png#172 = assets/alphaver/textures/block/celestial_flame.png
terrain.png#193 = assets/alphaver/textures/block/limestone.png
terrain.png#194 = assets/alphaver/textures/block/cobbled_limestone.png
terrain.png#267 = assets/alphaver/textures/block/hydrangea.png
terrain.png#269 = assets/alphaver/textures/block/hydrangea_fields.png
terrain.png#111 = assets/alphaver/textures/block/tallgrass.png
terrain.png#336 = assets/alphaver/textures/block/tallgrass_fields.png

terrain.png#182 = assets/alphaver/textures/block/flamewood_log.png
terrain.png#183 = assets/alphaver/textures/block/flamewood_leaves.png
terrain.png#184 = assets/alphaver/textures/block/flamewood_leaves_fast.png
terrain.png#323 = assets/alphaver/textures/block/tea_bush.png
terrain.png#324 = assets/alphaver/textures/block/tea_bush_fast.png
terrain.png#326 = assets/alphaver/textures/block/tea_wood_top.png
terrain.png#325 = assets/alphaver/textures/block/tea_wood_side.png
terrain.png#209 = assets/alphaver/textures/block/highwood_log_top.png
terrain.png#208 = assets/alphaver/textures/block/highwood_log_side.png
terrain.png#211 = assets/alphaver/textures/block/highwood_leaves.png
terrain.png#213 = assets/alphaver/textures/block/highwood_roots.png
terrain.png#131 = assets/alphaver/textures/block/frigid_trunk.png
terrain.png#224 = assets/alphaver/textures/block/frigid_leaves.png

terrain.png#181 = assets/alphaver/textures/block/low_lily.png
terrain.png#186 = assets/alphaver/textures/block/low_vine.png
terrain.png#180 = assets/alphaver/textures/block/low_riverbed.png
terrain.png#179 = assets/alphaver/textures/block/low_wart.png
terrain.png#187 = assets/alphaver/textures/block/low_river_stone.png
terrain.png#188 = assets/alphaver/textures/block/low_river_gold_ore.png
terrain.png#189 = assets/alphaver/textures/block/low_river_iron_ore.png
terrain.png#190 = assets/alphaver/textures/block/low_river_coal_ore.png
terrain.png#191 = assets/alphaver/textures/block/low_river_diamond_ore.png
terrain.png#192 = assets/alphaver/textures/block/low_river_greenstone_ore.png
terrain.png#246 = assets/alphaver/textures/block/lichen.png

terrain.png#295 = assets/alphaver/textures/block/low_mycon_top.png
terrain.png#296 = assets/alphaver/textures/block/low_mycon_side.png
terrain.png#299 = assets/alphaver/textures/block/mycon_stem_top.png
terrain.png#300 = assets/alphaver/textures/block/mycon_stem_side.png
terrain.png#301 = assets/alphaver/textures/block/mycon_cap.png
terrain.png#302 = assets/alphaver/textures/block/glowing_mycon_cap.png

terrain.png#311 = assets/alphaver/textures/block/bismuth_ore.png
terrain.png#368 = assets/alphaver/textures/block/lace_agate_ore.png
terrain.png#369 = assets/alphaver/textures/block/clinohumite_ore.png
terrain.png#370 = assets/alphaver/textures/block/malachite_ore.png
terrain.png#371 = assets/alphaver/textures/block/pyrite_ore.png

terrain.png#51 = assets/alphaver/textures/block/greenstone_ore.png, assets/alphaver/textures/block/greenstone_ore_glowing.png
terrain.png#84 = assets/alphaver/textures/block/greenstone_wire_cross.png
terrain.png#85 = assets/alphaver/textures/block/greenstone_wire_straight.png
terrain.png#100 = assets/alphaver/textures/block/greenstone_wire_cross_powered.png
terrain.png#101 = assets/alphaver/textures/block/greenstone_wire_straight_powered.png
terrain.png#115 = assets/alphaver/textures/block/greenstone_torch_idle.png
terrain.png#99 = assets/alphaver/textures/block/greenstone_torch_active.png

terrain.png#144 = assets/alphaver/textures/block/pillar.png
terrain.png#148 = assets/alphaver/textures/block/dimension_floor.png
terrain.png#149 = assets/alphaver/textures/block/dimension_wall.png
terrain.png#150 = assets/alphaver/textures/block/debug_block.png
terrain.png#151 = assets/alphaver/textures/block/dimension_tile_blue.png
terrain.png#152 = assets/alphaver/textures/block/dimension_tile_yellow.png
terrain.png#98 = assets/alphaver/textures/block/hub_door_lower.png
terrain.png#82 = assets/alphaver/textures/block/hub_door_upper.png
terrain.png#129 = assets/alphaver/textures/block/cypress_door_lower.png
terrain.png#113 = assets/alphaver/textures/block/cypress_door_upper.png
terrain.png#153 = assets/alphaver/textures/block/fake_grass_top.png
terrain.png#154 = assets/alphaver/textures/block/fake_grass_side.png
terrain.png#155 = assets/alphaver/textures/block/fake_grass_bottom.png
terrain.png#162 = assets/alphaver/textures/block/fake_dirt.png
terrain.png#163 = assets/alphaver/textures/block/fake_stone.png
terrain.png#164 = assets/alphaver/textures/block/fake_sand.png

terrain.png#195 = assets/alphaver/textures/block/smooth_stone.png
terrain.png#202 = assets/alphaver/textures/block/crude_pillar.png
terrain.png#252 = assets/alphaver/textures/block/flamewood_pillar.png
terrain.png#262 = assets/alphaver/textures/block/slate_bricks.png
terrain.png#265 = assets/alphaver/textures/block/slate_pillar_top.png
terrain.png#264 = assets/alphaver/textures/block/slate_pillar_side.png
terrain.png#178 = assets/alphaver/textures/block/wireframe_block.png
terrain.png#134 = assets/alphaver/textures/block/glass_blue.png
terrain.png#135 = assets/alphaver/textures/block/glass_green.png
terrain.png#136 = assets/alphaver/textures/block/glass_black.png
terrain.png#228 = assets/alphaver/textures/block/grass_pathway_top.png
terrain.png#229 = assets/alphaver/textures/block/grass_pathway_side.png
terrain.png#2 = assets/alphaver/textures/block/grass_pathway_bottom.png
terrain.png#62 = assets/alphaver/textures/block/solar_plate.png
terrain.png#63 = assets/alphaver/textures/block/denial_plate.png
terrain.png#77 = assets/alphaver/textures/block/switch_plate.png
terrain.png#78 = assets/alphaver/textures/block/loop_plate.png
terrain.png#79 = assets/alphaver/textures/block/part_plate.png
terrain.png#283 = assets/alphaver/textures/block/association_plate.png
terrain.png#282 = assets/alphaver/textures/block/trinity_plate.png
terrain.png#284 = assets/alphaver/textures/block/dialect_plate.png
terrain.png#285 = assets/alphaver/textures/block/syllables_plate.png
terrain.png#286 = assets/alphaver/textures/block/mirrors_plate.png

terrain.png#320 = assets/alphaver/textures/block/grass_fields_top.png
terrain.png#321 = assets/alphaver/textures/block/grass_fields_side.png
terrain.png#215 = assets/alphaver/textures/block/grass_highwood_top.png
terrain.png#214 = assets/alphaver/textures/block/grass_highwood_side.png

terrain.png#145 = assets/alphaver/textures/block/glass_fortified.png
terrain.png#117 = assets/alphaver/textures/block/glass_fortified_magenta.png
terrain.png#118 = assets/alphaver/textures/block/glass_fortified_blue.png
terrain.png#119 = assets/alphaver/textures/block/glass_fortified_green.png
terrain.png#120 = assets/alphaver/textures/block/glass_fortified_black.png
terrain.png#146 = assets/alphaver/textures/block/stone_tile.png
terrain.png#147 = assets/alphaver/textures/block/tile.png
terrain.png#165 = assets/alphaver/textures/block/cloth_magenta.png
terrain.png#166 = assets/alphaver/textures/block/cloth_blue.png
terrain.png#167 = assets/alphaver/textures/block/cloth_green.png
terrain.png#168 = assets/alphaver/textures/block/cloth_black.png
terrain.png#185 = assets/alphaver/textures/block/flamewood_planks.png
terrain.png#225 = assets/alphaver/textures/block/highwood_planks.png
terrain.png#304 = assets/alphaver/textures/block/mycon_planks.png
terrain.png#327 = assets/alphaver/textures/block/tea_planks.png
terrain.png#200 = assets/alphaver/textures/block/essence_cache.png
terrain.png#201 = assets/alphaver/textures/block/smooth_limestone.png
terrain.png#127 = assets/alphaver/textures/block/bookshelf_top.png
terrain.png#108 = assets/alphaver/textures/block/bookshelf_side.png
terrain.png#109 = assets/alphaver/textures/block/bookshelf_empty_side.png
terrain.png#35 = assets/alphaver/textures/block/cloth_panel_side.png
terrain.png#4 = assets/alphaver/textures/block/cloth_panel_end.png
terrain.png#103 = assets/alphaver/textures/block/lichen_bricks.png
terrain.png#245 = assets/alphaver/textures/block/lichen_mass.png
terrain.png#243 = assets/alphaver/textures/block/flame_glass_sky.png
terrain.png#247 = assets/alphaver/textures/block/flame_glass_gold.png
terrain.png#248 = assets/alphaver/textures/block/flame_glass_obsidian.png
terrain.png#249 = assets/alphaver/textures/block/flame_glass_low.png
terrain.png#204 = assets/alphaver/textures/block/gold_brick.png
terrain.png#236 = assets/alphaver/textures/block/obsidian_brick.png
terrain.png#221 = assets/alphaver/textures/block/diamond_brick.png
terrain.png#220 = assets/alphaver/textures/block/iron_brick.png
terrain.png#253 = assets/alphaver/textures/block/highwood_pillar.png
terrain.png#329 = assets/alphaver/textures/block/tea_pillar.png
terrain.png#316 = assets/alphaver/textures/block/mycon_pillar.png
terrain.png#315 = assets/alphaver/textures/block/bismuth_pillar_top.png
terrain.png#313 = assets/alphaver/textures/block/bismuth_pillar_side.png
terrain.png#303 = assets/alphaver/textures/block/salt_bricks.png
terrain.png#230 = assets/alphaver/textures/block/snow_brick.png
terrain.png#314 = assets/alphaver/textures/block/bismuth_brick.png
terrain.png#312 = assets/alphaver/textures/block/bismuth_block.png
terrain.png#346 = assets/alphaver/textures/block/lace_agate_block.png
terrain.png#347 = assets/alphaver/textures/block/clinohumite_block.png
terrain.png#348 = assets/alphaver/textures/block/malachite_block.png
terrain.png#291 = assets/alphaver/textures/block/pyrite_block.png

terrain.png#173 = assets/alphaver/textures/block/lily_flame.png
terrain.png#174 = assets/alphaver/textures/block/lily_gold.png
terrain.png#175 = assets/alphaver/textures/block/lily_obsidian.png

terrain.png#130 = assets/alphaver/textures/block/highwood_door_lower.png
terrain.png#114 = assets/alphaver/textures/block/highwood_door_upper.png
terrain.png#132 = assets/alphaver/textures/block/mycon_door_lower.png
terrain.png#116 = assets/alphaver/textures/block/mycon_door_upper.png
terrain.png#344 = assets/alphaver/textures/block/tea_door_lower.png
terrain.png#328 = assets/alphaver/textures/block/tea_door_upper.png
terrain.png#226 = assets/alphaver/textures/block/ice_door_lower.png
terrain.png#210 = assets/alphaver/textures/block/ice_door_upper.png

terrain.png#305 = assets/alphaver/textures/block/mycon_workbench_top.png
terrain.png#306 = assets/alphaver/textures/block/mycon_workbench_side.png
terrain.png#307 = assets/alphaver/textures/block/mycon_workbench_bottom.png
terrain.png#308 = assets/alphaver/textures/block/highwood_workbench_top.png
terrain.png#309 = assets/alphaver/textures/block/highwood_workbench_side.png
terrain.png#310 = assets/alphaver/textures/block/highwood_workbench_bottom.png
terrain.png#261 = assets/alphaver/textures/block/flamewood_workbench_top.png
terrain.png#277 = assets/alphaver/textures/block/flamewood_workbench_side.png
terrain.png#278 = assets/alphaver/textures/block/flamewood_workbench_bottom.png
terrain.png#330 = assets/alphaver/textures/block/tea_workbench_top.png
terrain.png#331 = assets/alphaver/textures/block/tea_workbench_side.png
terrain.png#332 = assets/alphaver/textures/block/tea_workbench_bottom.png
terrain.png#1 = assets/alphaver/textures/block/freezer_top.png
terrain.png#338 = assets/alphaver/textures/block/freezer_side.png
terrain.png#339 = assets/alphaver/textures/block/freezer_front.png
terrain.png#340 = assets/alphaver/textures/block/freezer_front_lit.png
terrain.png#141 = assets/alphaver/textures/block/essence_transformer_top.png
terrain.png#142 = assets/alphaver/textures/block/essence_transformer_side.png
terrain.png#143 = assets/alphaver/textures/block/essence_machine_bottom.png
terrain.png#125 = assets/alphaver/textures/block/essence_cloner_top.png
terrain.png#126 = assets/alphaver/textures/block/essence_cloner_side.png

terrain.png#156 = assets/alphaver/textures/block/mojang_block_blue.png
terrain.png#133 = assets/alphaver/textures/block/glass_magenta.png
terrain.png#198 = assets/alphaver/textures/block/glowing_cache.png
terrain.png#14 = assets/alphaver/textures/block/elder_decorated_stone.png
terrain.png#30 = assets/alphaver/textures/block/elder_brick.png
terrain.png#46 = assets/alphaver/textures/block/elder_pillar.png
terrain.png#110 = assets/alphaver/textures/block/elder_smooth_stone.png
terrain.png#244 = assets/alphaver/textures/block/gold_elder_brick.png
terrain.png#240 = assets/alphaver/textures/block/vending_health_boost_top.png
terrain.png#241 = assets/alphaver/textures/block/vending_health_boost_lower.png
terrain.png#242 = assets/alphaver/textures/block/vending_health_boost_upper.png
terrain.png#256 = assets/alphaver/textures/block/vending_armor_top.png
terrain.png#257 = assets/alphaver/textures/block/vending_armor_lower.png
terrain.png#258 = assets/alphaver/textures/block/vending_armor_upper.png
terrain.png#272 = assets/alphaver/textures/block/vending_dash_top.png
terrain.png#273 = assets/alphaver/textures/block/vending_dash_lower.png
terrain.png#274 = assets/alphaver/textures/block/vending_dash_upper.png
terrain.png#288 = assets/alphaver/textures/block/vending_quick_revive_top.png
terrain.png#289 = assets/alphaver/textures/block/vending_quick_revive_lower.png
terrain.png#290 = assets/alphaver/textures/block/vending_quick_revive_upper.png
terrain.png#233 = assets/alphaver/textures/block/weapon_upgrader_top.png
terrain.png#234 = assets/alphaver/textures/block/weapon_upgrader_side.png
terrain.png#250 = assets/alphaver/textures/block/decorative_block_1.png
terrain.png#251 = assets/alphaver/textures/block/decorative_block_2.png
terrain.png#263 = assets/alphaver/textures/block/slate_beacon.png
terrain.png#317 = assets/alphaver/textures/block/coal_brick.png
region:mob/zombie.png@8,8,8,8@scale=16x16 = assets/alphaver/textures/block/door_icon/zombies_cypress.png
terrain.png#15 = assets/alphaver/textures/block/door_icon/cypress_sapling.png

terrain.png#171@emissive=petals = assets/alphaver/textures/block/water_lily.emiss.png
terrain.png#172@emissive=all = assets/alphaver/textures/block/celestial_flame.emiss.png
terrain.png#173@emissive=petals = assets/alphaver/textures/block/lily_flame.emiss.png
terrain.png#174@emissive=petals = assets/alphaver/textures/block/lily_gold.emiss.png
terrain.png#175@emissive=petals = assets/alphaver/textures/block/lily_obsidian.emiss.png
terrain.png#181@emissive=pale = assets/alphaver/textures/block/low_lily.emiss.png
terrain.png#186@emissive=pale = assets/alphaver/textures/block/low_vine.emiss.png
terrain.png#179@emissive=pale = assets/alphaver/textures/block/low_wart.emiss.png
terrain.png#302@emissive=bright:0.28 = assets/alphaver/textures/block/glowing_mycon_cap.emiss.png
terrain.png#51@emissive=saturated:0.5 = assets/alphaver/textures/block/greenstone_ore_glowing.emiss.png
terrain.png#99@emissive=hue:90-150 = assets/alphaver/textures/block/greenstone_torch_active.emiss.png
terrain.png#62@emissive=all = assets/alphaver/textures/block/solar_plate.emiss.png
terrain.png#63@emissive=all = assets/alphaver/textures/block/denial_plate.emiss.png
terrain.png#77@emissive=all = assets/alphaver/textures/block/switch_plate.emiss.png
terrain.png#78@emissive=all = assets/alphaver/textures/block/loop_plate.emiss.png
terrain.png#79@emissive=all = assets/alphaver/textures/block/part_plate.emiss.png
terrain.png#283@emissive=all = assets/alphaver/textures/block/association_plate.emiss.png
terrain.png#282@emissive=all = assets/alphaver/textures/block/trinity_plate.emiss.png
terrain.png#284@emissive=all = assets/alphaver/textures/block/dialect_plate.emiss.png
terrain.png#285@emissive=all = assets/alphaver/textures/block/syllables_plate.emiss.png
terrain.png#286@emissive=all = assets/alphaver/textures/block/mirrors_plate.emiss.png
terrain.png#243@emissive=bright:0.85 = assets/alphaver/textures/block/flame_glass_sky.emiss.png
terrain.png#247@emissive=bright:0.85 = assets/alphaver/textures/block/flame_glass_gold.emiss.png
terrain.png#248@emissive=bright:0.85 = assets/alphaver/textures/block/flame_glass_obsidian.emiss.png
terrain.png#249@emissive=bright:0.85 = assets/alphaver/textures/block/flame_glass_low.emiss.png
terrain.png#346@emissive=bright:0.9 = assets/alphaver/textures/block/lace_agate_block.emiss.png
terrain.png#347@emissive=bright:0.9 = assets/alphaver/textures/block/clinohumite_block.emiss.png
terrain.png#348@emissive=bright:0.9 = assets/alphaver/textures/block/malachite_block.emiss.png
terrain.png#291@emissive=bright:0.9 = assets/alphaver/textures/block/pyrite_block.emiss.png
