gui/items.png#195 = assets/alphaver/textures/item/essence.png
gui/items.png#29 = assets/alphaver/textures/item/lace_agate.png
gui/items.png#13 = assets/alphaver/textures/item/clinohumite.png
gui/items.png#45 = assets/alphaver/textures/item/malachite.png
gui/items.png#61 = assets/alphaver/textures/item/pyrite.png
gui/items.png#254 = assets/alphaver/textures/item/bismuth_ingot.png
gui/items.png#211 = assets/alphaver/textures/item/granular_salt.png
gui/items.png#105 = assets/alphaver/textures/item/frigid_bits.png
gui/items.png#119 = assets/alphaver/textures/item/observer_fur.png
gui/items.png#56 = assets/alphaver/textures/item/greenstone.png

gui/items.png#248 = assets/alphaver/textures/item/pear.png
gui/items.png#249 = assets/alphaver/textures/item/obsidian_pear.png
gui/items.png#79 = assets/alphaver/textures/item/tea_leaf.png
gui/items.png#78 = assets/alphaver/textures/item/tea_bucket.png

gui/items.png#224 = assets/alphaver/textures/item/hours_long_past_1.png
gui/items.png#225 = assets/alphaver/textures/item/hours_long_past_2.png
gui/items.png#226 = assets/alphaver/textures/item/hours_long_past_3.png
gui/items.png#227 = assets/alphaver/textures/item/hours_long_past_4.png
gui/items.png#228 = assets/alphaver/textures/item/the_one_true_book.png

gui/items.png#73 = assets/alphaver/textures/item/rain_conch.png
gui/items.png#69 = assets/alphaver/textures/item/flameberge.png
gui/items.png#246 = assets/alphaver/textures/item/record_sandcastles.png
gui/items.png#212 = assets/alphaver/textures/item/record_rock_beetle.png
gui/items.png#242 = assets/alphaver/textures/item/record_downbeat_uplink.png
gui/items.png#247 = assets/alphaver/textures/item/record_k2.png
gui/items.png#250 = assets/alphaver/textures/item/record_desambrier.png
gui/items.png#251 = assets/alphaver/textures/item/record_juhry.png
gui/items.png#243 = assets/alphaver/textures/item/record_gyldan_sverd.png
gui/items.png#240 = assets/alphaver/textures/item/record_lemuria.png
gui/items.png#241 = assets/alphaver/textures/item/record_hidden_den.png

gui/items.png#208 = assets/alphaver/textures/item/obsidian_ingot.png
gui/items.png#146 = assets/alphaver/textures/item/dye_black.png
gui/items.png#147 = assets/alphaver/textures/item/dye_green.png
gui/items.png#148 = assets/alphaver/textures/item/dye_blue.png
gui/items.png#149 = assets/alphaver/textures/item/dye_pink.png
gui/items.png#255 = assets/alphaver/textures/item/mycon_strand.png
gui/items.png#162 = assets/alphaver/textures/item/fryshroom.png
gui/items.png#178 = assets/alphaver/textures/item/liquified_flame.png
gui/items.png#90 = assets/alphaver/textures/item/candy_ice.png

gui/items.png#145 = assets/alphaver/textures/item/obsidian_sword.png
gui/items.png#161 = assets/alphaver/textures/item/obsidian_shovel.png
gui/items.png#177 = assets/alphaver/textures/item/obsidian_pickaxe.png
gui/items.png#193 = assets/alphaver/textures/item/obsidian_axe.png
gui/items.png#209 = assets/alphaver/textures/item/obsidian_hoe.png
gui/items.png#144 = assets/alphaver/textures/item/obsidian_helm.png
gui/items.png#160 = assets/alphaver/textures/item/obsidian_chestplate.png
gui/items.png#176 = assets/alphaver/textures/item/obsidian_leggings.png
gui/items.png#192 = assets/alphaver/textures/item/obsidian_boots.png
gui/items.png#231 = assets/alphaver/textures/item/mycon_sword.png
gui/items.png#232 = assets/alphaver/textures/item/mycon_shovel.png
gui/items.png#233 = assets/alphaver/textures/item/mycon_pickaxe.png
gui/items.png#234 = assets/alphaver/textures/item/mycon_axe.png
gui/items.png#235 = assets/alphaver/textures/item/mycon_hoe.png
gui/items.png#85 = assets/alphaver/textures/item/spear.png
gui/items.png#89 = assets/alphaver/textures/item/hearthen_mirror.png
gui/items.png#180 = assets/alphaver/textures/item/essence_rifle.png
gui/items.png#179 = assets/alphaver/textures/item/door_flamewood.png
gui/items.png#253 = assets/alphaver/textures/item/door_highwood.png
gui/items.png#252 = assets/alphaver/textures/item/door_mycon.png
gui/items.png#86 = assets/alphaver/textures/item/door_tea.png
gui/items.png#91 = assets/alphaver/textures/item/door_ice.png

gui/items.png#238 = assets/alphaver/textures/item/gray_gun.png
gui/items.png#194 = assets/alphaver/textures/item/eraser.png
gui/items.png#150 = assets/alphaver/textures/item/stylish_visor.png
gui/items.png#166 = assets/alphaver/textures/item/stylish_chestplate.png
gui/items.png#182 = assets/alphaver/textures/item/stylish_shorts.png
gui/items.png#198 = assets/alphaver/textures/item/stylish_shoes.png
gui/items.png#210 = assets/alphaver/textures/item/sunglasses.png

region:gui/icons.png@0,16,9,9 = assets/alphaver/textures/gui/sprites/hud/frail.png

region:gui/icons.png@0,27,32,16 = assets/alphaver/textures/gui/sprites/hud/lilypad_hunger/frame.png
region:gui/icons.png@0,43,32,16 = assets/alphaver/textures/gui/sprites/hud/lilypad_hunger/fill_0.png
region:gui/icons.png@32,43,32,16 = assets/alphaver/textures/gui/sprites/hud/lilypad_hunger/fill_1.png
region:gui/icons.png@64,43,32,16 = assets/alphaver/textures/gui/sprites/hud/lilypad_hunger/fill_2.png
region:gui/icons.png@96,43,32,16 = assets/alphaver/textures/gui/sprites/hud/lilypad_hunger/fill_3.png

region:gui/zm_perks.png@32,0,32,32 = assets/alphaver/textures/gui/sprites/hud/zm_perks/health_boost.png
region:gui/zm_perks.png@64,0,32,32 = assets/alphaver/textures/gui/sprites/hud/zm_perks/armor.png
region:gui/zm_perks.png@96,0,32,32 = assets/alphaver/textures/gui/sprites/hud/zm_perks/dash.png
region:gui/zm_perks.png@128,0,32,32 = assets/alphaver/textures/gui/sprites/hud/zm_perks/quick_revive.png

region:particles.png@0,40,8,8 = assets/alphaver/textures/particle/leaf.png
region:particles.png@24,40,8,8 = assets/alphaver/textures/particle/snow_1.png
region:particles.png@32,40,8,8 = assets/alphaver/textures/particle/snow_2.png
region:particles.png@40,40,8,8 = assets/alphaver/textures/particle/snow_3.png
region:particles.png@0,32,8,8 = assets/alphaver/textures/particle/snowflake_1.png
region:particles.png@8,32,8,8 = assets/alphaver/textures/particle/snowflake_2.png
region:particles.png@16,32,8,8 = assets/alphaver/textures/particle/snowflake_3.png

gui/items.png#178@emissive=all = assets/alphaver/textures/item/liquified_flame.emiss.png
